# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- build-pipeline

pool:
  vmImage: 'Ubuntu-latest'
  demands:
    - npm
    
steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.1.505'
  inputs:
    version: 2.1.505

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'
  
- task: gulp@1
  displayName: 'Run gulp tasks'

- script: echo This is the result from echoing a one-liner...
  displayName: 'Run a one-line script'

- script: |
    echo What is your name, and who is your daddy?
    echo Is he rich like me?
  displayName: 'Run a multi-line script'
